apiVersion: 1

contactPoints:
  - orgId: 1
    name: Tikitaka Slack
    receivers:
      - uid: tikitaka-slack
        type: slack
        disableResolveMessage: false
        settings:
          recipient: $SLACK_RECIPIENT
          url: $SLACK_WEBHOOK_URL
          username: TIKITAKA Grafana
