spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5435/tikitaka_payment
    username: payment
    password: payment_local_password
  kafka:
    bootstrap-servers: localhost:9092
