spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:payment-postgres}:${PAYMENT_DB_PORT:5432}/${PAYMENT_DB_NAME:tikitaka_payment}
    username: ${PAYMENT_DB_USERNAME:payment}
    password: ${PAYMENT_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:19092}
