spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://payment-postgres:5432/${PAYMENT_DB_NAME}
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}
  kafka:
    bootstrap-servers: kafka:19092
