spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://platform-postgres:5432/${PLATFORM_DB_NAME}
    username: ${PLATFORM_DB_USERNAME}
    password: ${PLATFORM_DB_PASSWORD}
  data:
    redis:
      host: platform-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:19092
