spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:postgresql://${STAGING_DATA_PRIVATE_IP}:5433/${PLATFORM_DB_NAME}
    username: ${PLATFORM_DB_USERNAME}
    password: ${PLATFORM_DB_PASSWORD}
  data:
    redis:
      host: ${STAGING_DATA_PRIVATE_IP}
      port: 6380
  kafka:
    bootstrap-servers: ${STAGING_DATA_PRIVATE_IP}:9092

clients:
  ticketing-service:
    url: ${TICKETING_SERVICE_URL}

# 일반 API와 분리된 모니터링용 Actuator 관리 포트
# health 및 Prometheus 메트릭 엔드포인트만 노출
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
