spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${PLATFORM_DB_HOST:platform-postgres}:${PLATFORM_DB_PORT:5432}/${PLATFORM_DB_NAME:tikitaka_platform}
    username: ${PLATFORM_DB_USERNAME:platform}
    password: ${PLATFORM_DB_PASSWORD}
  data:
    redis:
      host: ${PLATFORM_REDIS_HOST:platform-redis}
      port: ${PLATFORM_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:19092}
