spring:
  config:
    activate:
      on-profile: docker

services:
  platform:
    url: http://platform-service:8081
  ticketing:
    url: http://ticketing-service:8082
  payment-notification:
    url: http://payment-notification-service:8083
