spring:
  config:
    activate:
      on-profile: local

services:
  platform:
    url: http://localhost:8081
  ticketing:
    url: http://localhost:8082
  payment-notification:
    url: http://localhost:8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Platform Service
        url: /openapi/platform
      - name: Ticketing Service
        url: /openapi/ticketing
      - name: Payment & Notification Service
        url: /openapi/payment-notification
