spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://ticketing-postgres:5432/${TICKETING_DB_NAME}
    username: ${TICKETING_DB_USERNAME}
    password: ${TICKETING_DB_PASSWORD}
  data:
    redis:
      host: ticketing-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:19092

clients:
  platform-service:
    url: http://platform-service:8081
