spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:postgresql://${STAGING_DATA_PRIVATE_IP}:5434/${TICKETING_DB_NAME}
    username: ${TICKETING_DB_USERNAME}
    password: ${TICKETING_DB_PASSWORD}
  data:
    redis:
      host: ${STAGING_DATA_PRIVATE_IP}
      port: 6381
  kafka:
    bootstrap-servers: ${STAGING_DATA_PRIVATE_IP}:9092

clients:
  platform-service:
    url: ${PLATFORM_SERVICE_URL}
  payment-notification-service:
    url: ${PAYMENT_NOTIFICATION_SERVICE_URL}

# 일반 API와 분리된 모니터링용 Actuator 관리 포트
# health 및 Prometheus 메트릭 엔드포인트만 노출
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
