server:
  port: 8082

spring:
  application:
    name: ticketing-service
  cloud:
    openfeign:
      client:
        config:
          platformSalesStatusClient:
            connectTimeout: 1000
            readTimeout: 2000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

queue:
  admission-token-ttl: PT10M
  retention-after-sales-close: PT1H
  admission-batch-size: 50
  expiration-batch-size: 50
  admission-interval: PT1S

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
