spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://ticketing-postgres:5432/tikitaka_ticketing
    username: ticketing
    password: ticketing_local_password
  data:
    redis:
      host: ticketing-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:19092
