spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${TICKETING_DB_HOST:localhost}:${TICKETING_DB_PORT:5434}/${TICKETING_DB_NAME:tikitaka_ticketing}
    username: ${TICKETING_DB_USERNAME:ticketing}
    password: ${TICKETING_DB_PASSWORD}
  data:
    redis:
      host: ${TICKETING_REDIS_HOST:localhost}
      port: ${TICKETING_REDIS_PORT:6381}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
