spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5434/${TICKETING_DB_NAME}
    username: ${TICKETING_DB_USERNAME}
    password: ${TICKETING_DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6381
  kafka:
    bootstrap-servers: localhost:9092

clients:
  platform-service:
    url: http://localhost:8081
