apiVersion: 1

datasources:
  # Grafana 시작 시 Prometheus 데이터소스 자동 등록
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true # 로컬에서는 UI 수정 허용