-- =========================================================
-- Platform Service initial schema
-- =========================================================

-- 사용자
CREATE TABLE p_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_nickname UNIQUE (nickname),
    CONSTRAINT ck_user_role CHECK (role IN ('USER', 'ORGANIZER', 'ADMIN')),
    CONSTRAINT ck_user_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE UNIQUE INDEX uq_user_email_lower ON p_user (LOWER(email));

-- 공연 주최자
CREATE TABLE p_organizer (
    id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    representative_name VARCHAR(100) NOT NULL,
    contact_email VARCHAR(100) NOT NULL,
    contact_phone VARCHAR(20),
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at TIMESTAMPTZ,
    CONSTRAINT pk_organizer PRIMARY KEY (id),
    CONSTRAINT fk_organizer_user FOREIGN KEY (user_id) REFERENCES p_user (id) ON DELETE RESTRICT,
    CONSTRAINT uq_organizer_user_id UNIQUE (user_id),
    CONSTRAINT ck_organizer_status CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'REJECTED'))
);

-- 공연장
CREATE TABLE p_venue (
    id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    address VARCHAR(255) NOT NULL,
    address_detail VARCHAR(255),
    contact_phone VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_venue PRIMARY KEY (id)
);

-- 공연장 구역
CREATE TABLE p_venue_section (
    id UUID NOT NULL,
    venue_id UUID NOT NULL,
    name VARCHAR(50) NOT NULL,
    floor_label VARCHAR(20),
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_venue_section PRIMARY KEY (id),
    CONSTRAINT fk_venue_section_venue FOREIGN KEY (venue_id) REFERENCES p_venue (id) ON DELETE RESTRICT,
    CONSTRAINT uq_venue_section_venue_name UNIQUE (venue_id, name),
    CONSTRAINT ck_venue_section_display_order CHECK (display_order >= 0)
);

-- 공연장 좌석
CREATE TABLE p_venue_seat (
    id UUID NOT NULL,
    section_id UUID NOT NULL,
    row_label VARCHAR(20) NOT NULL,
    seat_number VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_venue_seat PRIMARY KEY (id),
    CONSTRAINT fk_venue_seat_section FOREIGN KEY (section_id) REFERENCES p_venue_section (id) ON DELETE RESTRICT,
    CONSTRAINT uq_venue_seat_section_row_number UNIQUE (section_id, row_label, seat_number)
);

-- 공연
CREATE TABLE p_event (
    id UUID NOT NULL,
    organizer_id UUID NOT NULL,
    venue_id UUID NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    running_time_minutes INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES p_organizer (id) ON DELETE RESTRICT,
    CONSTRAINT fk_event_venue FOREIGN KEY (venue_id) REFERENCES p_venue (id) ON DELETE RESTRICT,
    CONSTRAINT ck_event_running_time CHECK (running_time_minutes > 0),
    CONSTRAINT ck_event_status CHECK (status IN ('DRAFT', 'UPCOMING', 'ON_SALE', 'SALE_CLOSED', 'COMPLETED', 'CANCELED'))
);

-- 공연 회차
CREATE TABLE p_event_session (
    id UUID NOT NULL,
    event_id UUID NOT NULL,
    session_number INTEGER NOT NULL,
    performance_start_at TIMESTAMPTZ NOT NULL,
    performance_end_at TIMESTAMPTZ NOT NULL,
    sales_open_at TIMESTAMPTZ NOT NULL,
    sales_close_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    CONSTRAINT pk_event_session PRIMARY KEY (id),
    CONSTRAINT fk_event_session_event FOREIGN KEY (event_id) REFERENCES p_event (id) ON DELETE CASCADE,
    CONSTRAINT uq_event_session_event_number UNIQUE (event_id, session_number),
    CONSTRAINT ck_event_session_number CHECK (session_number > 0),
    CONSTRAINT ck_event_session_time CHECK (sales_open_at < sales_close_at AND sales_close_at <= performance_start_at AND performance_start_at < performance_end_at),
    CONSTRAINT ck_event_session_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELED'))
);

-- 회차별 구역 가격 정책
CREATE TABLE p_session_section_price (
    id UUID NOT NULL,
    event_session_id UUID NOT NULL,
    venue_section_id UUID NOT NULL,
    seat_grade VARCHAR(30) NOT NULL,
    price_amount BIGINT NOT NULL,
    sales_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_session_section_price PRIMARY KEY (id),
    CONSTRAINT fk_session_section_price_session FOREIGN KEY (event_session_id) REFERENCES p_event_session (id) ON DELETE CASCADE,
    CONSTRAINT fk_session_section_price_section FOREIGN KEY (venue_section_id) REFERENCES p_venue_section (id) ON DELETE RESTRICT,
    CONSTRAINT uq_session_section_price_session_section UNIQUE (event_session_id, venue_section_id),
    CONSTRAINT ck_session_section_price_amount CHECK (price_amount >= 0)
);
